project_id = "riqqyhaguckeijcownor"

[functions.enhance-pass]
verify_jwt = true

[functions.check-expiring-passes]
verify_jwt = false

[functions.respond-to-alert]
verify_jwt = true

[functions.create-test-alert]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.get-signed-url]
verify_jwt = true
